const PLACES_ACTION_TYPES = {
  FETCH_PLACES_START: 'places/FETCH_PLACES_START',
  FETCH_PLACES_SUCCESS: 'places/FETCH_PLACES_SUCCESS',
  FETCH_PLACES_FAILED: 'places/FETCH_PLACES_FAILED',
  CLEAR_PLACES: 'places/CLEAR_PLACES'
};

export default PLACES_ACTION_TYPES;