const TIPS_ACTION_TYPES = {
  FETCH_TIPS_START: 'tips/FETCH_TIPS_START',
  FETCH_TIPS_SUCCESS: 'tips/FETCH_TIPS_SUCCESS',
  FETCH_TIPS_FAILED: 'tips/FETCH_TIPS_FAILED',
};

export default TIPS_ACTION_TYPES;