const PHOTOS_ACTION_TYPES = {
  FETCH_PHOTOS_START: 'places/FETCH_PHOTOS_START',
  FETCH_PHOTOS_SUCCESS: 'photos/FETCH_PHOTOS_SUCCESS',
  FETCH_PHOTOS_FAILED: 'photos/FETCH_PHOTOS_FAILED',
  CLEAR_PHOTOS: 'photos/CLEAR_PHOTOS'
};

export default PHOTOS_ACTION_TYPES;