const FORECAST_ACTION_TYPES = {
  FETCH_FORECAST_START: 'forecast/FETCH_FORECAST_START',
  FETCH_FORECAST_SUCCESS: 'forecast/FETCH_FORECAST_SUCCESS',
  FETCH_FORECAST_FAILED: 'forecast/FETCH_FORECAST_FAILED'
};

export default FORECAST_ACTION_TYPES;